name: simple-python-stack
channels:
  - conda-forge
  - plotly
dependencies:
  - numpy
  - matplotlib
  - seaborn
  - pandas
  - scipy
  - sympy
  - numba
  - plotly
  - plotly-orca
  - scikit-learn
  - psutil
  - requests
  - pip
  - pip:
    - pydataset
    - voyager-launch
